version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx 
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # this will not copy node_modules from local machine
      - '/app/node_modules'
      # will copy from server to app folder for developing
      - './server:/app'
    environment:
      #redis it's means a API that contain redis conteiner 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      #redis it's means a API that contain postgres conteiner 
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    depends_on:
      - postgres  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - '/app/node_modules'
      - './worker:/app'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379